### ISSUE TITLE
Improve Bracken execution docs

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#261]
### Description of the bug

As reported by @alexhbnr 

See comment below - could also make sure that it's clear eveywhere you must explicitly turn on kraken if you also want brakcen results

**Comment by alexhbnr** [comment]
To give some context, I don't think that the description about running Kraken2 before Bracken is misleading. I concluded this from the explanation. However, the database example mislead me because Bracken and Kraken2 aren't using the same database:

> An example database sheet can look as follows, where 5 tools are being used, and malt and kraken2 will be used against two databases each. This is because specifying bracken implies first running kraken2 on the same database.

```
tool,db_name,db_params,db_path
bracken,db1,;-r 150,/<path>/<to>/bracken/testdb-bracken.tar.gz
kraken2,db2,--quick,/<path>/<to>/kraken2/testdb-kraken2.tar.gz
krakenuniq,db3,,/<path>/<to>/krakenuniq/testdb-krakenuniq.tar.gz
```

Maybe clarifying the naming scheme in the database list does the trick already.

**Comment by jfy133** [comment]
Thanks for the clarification!

**Comment by Midnighter** [comment]
Or should we run kraken2 by default when `run_bracken` was chosen?
