### ISSUE TITLE
Unclear points in documentation

### ISSUE THREAD

**Issue by prototaxites** [nf-core/taxprofiler#267]
### Description of the bug

Hi all, a couple of points for the documentation that need clarifying:

1. In the additional help dropdown on the params page, the text for, `--run_profile_standardisation` states “This currently only is generated for mOTUs.“, but enabling this option turns on standardisation for all profilers. 

2. The Multi-Table Generation section of the usage guide does not supply the required parameter (`--run_profile_standardisation`) in order to enable consolidation of profiling reports.

3. The tutorial section on installing/downloading the mOTUs database should make clear that the name of the mOTUs database directory should not be changed (from `db_mOTU`) if it is moved from the install location. I initially renamed the directory when moving it to a centralised location and mOTUs refused to run as the directory name is hard-coded.

**Comment by jfy133** [comment]
- [ ] In the additional help dropdown on the params page, the text for, --run_profile_standardisation states “This currently only is generated for mOTUs.“, but enabling this option turns on standardisation for all profilers.
- [ ] The Multi-Table Generation section of the usage guide does not supply the required parameter (--run_profile_standardisation) in order to enable consolidation of profiling reports.
- [ ] The tutorial section on installing/downloading the mOTUs database should make clear that the name of the mOTUs database directory should not be changed (from db_mOTU) if it is moved from the install location. I initially renamed the directory when moving it to a centralised location and mOTUs refused to run as the directory name is hard-coded.
