### ISSUE TITLE
Add maxForks to MALT in test profile

### ISSUE THREAD

**Issue by jfy133** [nf-core/taxprofiler#61]
It's a hungry beast and can cause slow down on smaller machines (laptops) if it tries to run both DBs in parallel

**Comment by Midnighter** [comment]
Does that mean MALT does not respect the given `task.cpus`?

**Comment by jfy133** [comment]
No it does, I think it's the stupid way Java deals with _memory_ is the Problem. It'll try to use all the memory of the machine, and when running with smaller memory machines this can cause a lock up.

**Comment by Midnighter** [comment]
Maybe you need a local config to change the pipeline defaults when running on your laptop? I think it's really preferable to set the resource limits such that nextflow can schedule the tasks optimally rather than setting `maxForks`. I use `maxForks` for local executions sometimes but when I run on AWS, for example, I would not want to be limited by default.

**Comment by jfy133** [comment]
Hmmm, I see what you mean. But I only suggest adding it to the test profile - this jobs SHOULD be short anyway (so wouldn't really make much difference  if running in the cloud/HPC etc.), so the effect should be minimal. Also I would assume in most cases people would run the test profile on their laptop/local machine..., and I'm quite concerned people would be put off of using the pipeline if even `test` doesn't run nicely...

**Comment by Midnighter** [comment]
I should learn to read properly 🤦🏼‍♂️ Yes, makes a lot of sense for the test profile.
